### ISSUE TITLE
Question: How to integrate fork

### ISSUE THREAD

**Issue by alastair-todd** [michalkotas/angular2-jsonapi#5]
Hey

I am struggling to integrate the fork in my angular project

After I

```
npm i michalkotas/angular2-jsonapi
```

The imports to the project are not found.

![image](https://github.com/michalkotas/angular2-jsonapi/assets/595192/378d1029-a202-4186-9586-26b5f2f203c9)

**Comment by michalkotas** [comment]
This package is so called scoped package - you need to add scope prefix:

`import { JsonApiModule } from '@michalkotas/angular2-jsonapi';`
